s=input("Enter any string")
print(s.isalnum())
print(s.isalpha())
print(s.islower())
print(s.isupper())
print(s.isdigit())
print(s.istitle())
print(s.isspace())
print('Durga786'.isalnum())
print('Durga786'.isalpha())
print('durga786'.isalpha())
print('durga'.isdigit())
print('786786'.isdigit())
print('abc'.islower())
print('Abc'.islower())
print('abc123'.islower())
print('ABC'.isupper())
print("Durga Software Solutions".istitle())
print("Durga Software Solutions".istitle())
print(' '.isspace())